/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MediaGastoGasolina;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        
        float disTotalPercorrida = 0;
        float totCombustivel = 0;
        float mediaCombustivelGasto  = 0;
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.print("Qual a distancia percorrida km: ");
        disTotalPercorrida = leitor.nextFloat();
        
        System.out.print("Total combustivl gasto: ");
        totCombustivel = leitor.nextFloat();
        
        mediaCombustivelGasto = disTotalPercorrida / totCombustivel;
        
        System.out.print("A media de combustivel gasto por km: " + mediaCombustivelGasto);
        
        
        
    }
}
